import type { Metadata } from "next";
import RootLayoutWrapper from "@/components/layout/RootLayout";
import "./globals.css";
import { Poppins, Montserrat, Inter } from "next/font/google";
import { CartProvider } from "@/components/products/CartContext";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "INSPACE STORES",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});

// JSON-LD data
const jsonLd = {
  "@context": "https://schema.org/",
  "@type": "Product",
  "name": "Inspace Stores",
  "image": "https://www.inspacestore.in/assets/logo.svg",
  "description": "Inspace Store is a leading rack manufacturer in Chennai, specializing in manufacturing high-quality steel racks for supermarkets, retail stores, and industrial storage solutions.",
  "brand": {
    "@type": "Brand",
    "name": "Inspace Stores"
  },
  "offers": {
    "@type": "AggregateOffer",
    "url": "https://www.inspacestore.in/",
    "priceCurrency": "INR",
    "lowPrice": "",
    "offerCount": "542"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.8",
    "bestRating": "5",
    "worstRating": "1",
    "ratingCount": "495"
  }
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${montserrat.variable} ${inter.variable}`}
    >
      <head>
        <meta
          name="google-site-verification"
          content="3ga0oSQ978vsKILYYrvV4TE7LtNNU-7OdQgok9y1IXo"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <CartProvider>
          <Toaster className="!top-28 right-5" position="top-right" richColors />
          <RootLayoutWrapper>
            {children}
          </RootLayoutWrapper>
        </CartProvider>
      </body>
    </html>
  );
}
